# Creating Tensors with `tf.Variable()` Function
A `tf.variable` maintains shared, persistent state manipulated by a program.

The `Variable()` constructor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

In [6]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


### Create the same tensor with `tf.Varible()`

In [7]:
var_tensor = tf.Variable([4, 8])
const_tensor = tf.constant([4, 8])
print(var_tensor)
print(const_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 8])>
tf.Tensor([4 8], shape=(2,), dtype=int32)


Let's try to change one of the elements in our varible tensors with the help of `.assign()`.

In [10]:
var_tensor[0].assign(8)
print(var_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 8])>


Now, this time we are going to try the same operation with constant tensor.

In [11]:
const_tensor[0].assign(8)
print(const_tensor)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

This operation clearly shows that constant tensors does not support item assignment.

# Working with random tensors in Tensorflow
So, the first question which comes to our mind is what is a random tensor and what is it used for ?. 

So, Random tensors are tensors of some arbitrary size which contain random numbers. One of the common application of random tensors is to initalize weights in a neural network.

In [12]:
# Let's create the random tensors
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3, 2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>